### ISSUE TITLE
Next Button

### ISSUE THREAD

**Issue by Hopelezz** [DekotaNelson/100devs-follow-along-site#1]
The Next Class buttons don't "Feel" like buttons.

![image](https://user-images.githubusercontent.com/72772558/169717991-2288105b-83cf-4771-bc86-9663986dd179.png)

```
HTML:
<div>
	<mark class="nextClassButton" > Next Class </mark>
</div>
```

```
CSS:
mark {
	background-color: transparent;
	color: inherit;
}
```

**Comment by Cevocey** [comment]
I'll make this button feel like a button.

**Comment by DekotaNelson** [comment]
> I'll make this button feel like a button.

Class 35's HTML file has the new button layout, it just has to be copy pasted as a replacement for the old buttons in all the other class HTML files 👍

**Comment by Hopelezz** [comment]
Awesome.
