### ISSUE TITLE
javascript-crash-course next class link broken

### ISSUE THREAD

**Issue by mac-kenzie-lee** [DekotaNelson/100devs-follow-along-site#8]
Hey, from this page: https://100devsfollowalong.netlify.app/classes/javascript-crash-course.html
The next class button triggers an alert of 'we don't have that class yet'
![image](https://user-images.githubusercontent.com/106789729/194951212-42e44a59-d6ca-48f4-9afd-5a50254f5ea9.png)

Can this link get updated?

**Comment by Dedsecproject** [comment]
The button has been removed when I attempted to verify this!

**Comment by DekotaNelson** [comment]
Thanks for letting us know about this issue. The JavaScript Crash Course is a review/office hours video and not a regular class, so it wasn't intended to have a next/previous class option. I fixed this when adding the new classes.
